### ISSUE TITLE
internal package is not available

### ISSUE THREAD

**Issue by farwydi** [danl5/goelect#17]
this library cannot be used since the model package is internal

```
github.com/danl5/goelect/internal/model
```

if you don't use calls it will lead to an error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104e72bc0]

goroutine 24 [running]:
github.com/danl5/goelect.(*Elect).handleStateTransition(0x1400012b440, {0x104f542e8, 0x10515d580}, 0x1400010e6c0)
        /Users/l.zharikov/go/pkg/mod/github.com/danl5/goelect@v1.0.1/elect.go:199 +0x2d0
created by github.com/danl5/goelect.(*Elect).Run in goroutine 3
        /Users/l.zharikov/go/pkg/mod/github.com/danl5/goelect@v1.0.1/elect.go:111 +0x21c
```

**Comment by danl5** [comment]
Thanks for bringing this up, I can't believe I overlooked it, will fix it soon!

**Comment by danl5** [comment]
As a library project, perhaps the internal implementation should be more accessible, so switching from **internal** to **pkg**.
https://github.com/danl5/goelect/commit/ab6187d0e6946a4015c8f377060cbd4c47fd67dc

**Comment by danl5** [comment]
#19
