### ISSUE TITLE
Consensus data race

### ISSUE THREAD

**Issue by dimaxgl** [danl5/goelect#27]
Looks like consensus structure had problems with data races in internal channel usage. It was detected with go test with race flag:

```
==================
WARNING: DATA RACE
Read at 0x00c000392520 by goroutine 42:
  github.com/danl5/goelect/pkg/consensus.(*Consensus).RequestVote()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:183 +0x1fc
  github.com/danl5/goelect/pkg/consensus.(*Consensus).HandleRequest()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:130 +0x6d8
  github.com/danl5/goelect/pkg/consensus.(*Consensus).HandleRequest-fm()
      <autogenerated>:1 +0x44
  github.com/danl5/goelect/pkg/transport/rpc.(*RPCHandler).Handle()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/transport/rpc/rpc.go:51 +0x50
  runtime.call32()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:504 +0x74
  reflect.Value.Call()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/reflect/value.go:380 +0x90
  net/rpc.(*service).call()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/net/rpc/server.go:381 +0x1f0
  net/rpc.(*Server).ServeCodec.gowrap1()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/net/rpc/server.go:478 +0xd4

Previous write at 0x00c000392520 by goroutine 35:
  github.com/danl5/goelect/pkg/consensus.(*termCache).incrementByOne()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:788 +0x148
  github.com/danl5/goelect/pkg/consensus.(*Consensus).tryToBecomeLeader()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:489 +0x10c
  github.com/danl5/goelect/pkg/consensus.(*Consensus).runCandidate()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:466 +0x50
  github.com/danl5/goelect/pkg/consensus.(*Consensus).enterCandidate.func1()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:452 +0x44

Goroutine 42 (running) created at:
  net/rpc.(*Server).ServeCodec()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/net/rpc/server.go:478 +0x4c0
  github.com/danl5/goelect/pkg/transport/rpc.(*Server).startServer.func1.gowrap1()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/transport/rpc/rpc.go:167 +0x4c

Goroutine 35 (running) created at:
  github.com/danl5/goelect/pkg/consensus.(*Consensus).enterCandidate()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:451 +0x1e4
  github.com/danl5/goelect/pkg/consensus.(*Consensus).enterCandidate-fm()
      <autogenerated>:1 +0x4c
  github.com/looplab/fsm.(*FSM).enterStateCallbacks()
      /Users/dimaxgl/go/pkg/mod/github.com/looplab/fsm@v1.0.1/fsm.go:470 +0xb4
  github.com/looplab/fsm.(*FSM).Event.(*FSM).Event.func2.func3()
      /Users/dimaxgl/go/pkg/mod/github.com/looplab/fsm@v1.0.1/fsm.go:363 +0x1c4
  github.com/looplab/fsm.transitionerStruct.transition()
      /Users/dimaxgl/go/pkg/mod/github.com/looplab/fsm@v1.0.1/fsm.go:422 +0x80
  github.com/looplab/fsm.(*transitionerStruct).transition()
      <autogenerated>:1 +0x20
  github.com/looplab/fsm.(*FSM).doTransition()
      /Users/dimaxgl/go/pkg/mod/github.com/looplab/fsm@v1.0.1/fsm.go:407 +0xabc
  github.com/looplab/fsm.(*FSM).Event()
      /Users/dimaxgl/go/pkg/mod/github.com/looplab/fsm@v1.0.1/fsm.go:390 +0xaa4
  github.com/danl5/goelect/pkg/consensus.(*Consensus).runEventHandler.func1()
      /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.4/pkg/consensus/consensus.go:571 +0xd0
==================
```

**Comment by danl5** [comment]
Hi @dimaxgl, could you please provide your Go version and try with the new code version **v1.0.5**? I ran `go test -race` on my end and didn't detect the date race in `pkg/consensus`.
```
$ go test -race ./pkg/consensus
ok      github.com/danl5/goelect/pkg/consensus
```

**Comment by dimaxgl** [comment]
My version is `go1.22.5 darwin/arm64`
Looks like corresponding error caused by mistake in another place.
If I try to start to create multiple election endpoints locally in cycle I get next stacktrace:
```
2024/07/11 14:33:25 INFO rpc server started component="rpc server" listenAddress=127.0.0.1:57327
2024/07/11 14:33:25 INFO success to init transport component=consensus
2024/07/11 14:33:25 INFO become follower component=consensus
2024/07/11 14:33:25 INFO consensus started component=consensus
2024/07/11 14:33:25 INFO elect started component=elect
2024/07/11 14:33:25 INFO leave follower state due to heartbeat timeout component=consensus
2024/07/11 14:33:25 INFO leave follower component=consensus
2024/07/11 14:33:25 INFO become candidate component=consensus
2024/07/11 14:33:25 INFO received more than half of the votes, try to become leader component=consensus
2024/07/11 14:33:25 INFO leave candidate component=consensus
2024/07/11 14:33:25 INFO become leader component=consensus
2024/07/11 14:33:25 0
2024/07/11 14:33:25 INFO rpc server started component="rpc server" listenAddress=127.0.0.1:57328
2024/07/11 14:33:25 INFO success to init transport component=consensus
2024/07/11 14:33:25 INFO become follower component=consensus
2024/07/11 14:33:25 INFO consensus started component=consensus
2024/07/11 14:33:25 INFO elect started component=elect
2024/07/11 14:33:25 1
2024/07/11 14:33:25 INFO rpc server started component="rpc server" listenAddress=127.0.0.1:57329
2024/07/11 14:33:25 INFO success to init transport component=consensus
2024/07/11 14:33:25 INFO become follower component=consensus
2024/07/11 14:33:25 INFO consensus started component=consensus
2024/07/11 14:33:25 INFO elect started component=elect
2024/07/11 14:33:25 INFO leave follower state due to heartbeat timeout component=consensus
2024/07/11 14:33:25 INFO leave follower component=consensus
2024/07/11 14:33:25 INFO become candidate component=consensus
2024/07/11 14:33:25 INFO leave follower state due to heartbeat timeout component=consensus
2024/07/11 14:33:25 INFO leave follower component=consensus
2024/07/11 14:33:25 INFO become candidate component=consensus
2024/07/11 14:33:25 INFO send vote request to peer component=consensus peer=0
2024/07/11 14:33:25 INFO receive vote request component=consensus peer=1
2024/07/11 14:33:25 INFO receive vote request component=consensus from=127.0.0.1:57329 term=1 "current term"=0
2024/07/11 14:33:25 INFO vote for component=consensus node=0 term=1
2024/07/11 14:33:25 INFO leave candidate component=consensus
2024/07/11 14:33:25 INFO become follower component=consensus
2024/07/11 14:33:25 INFO get voting component=consensus peer=0
2024/07/11 14:33:25 INFO receive vote component=consensus peer=127.0.0.1:57328
2024/07/11 14:33:25 INFO received more than half of the votes, become leader component=consensus
2024/07/11 14:33:25 INFO leave candidate component=consensus
2024/07/11 14:33:25 INFO become leader component=consensus
2024/07/11 14:33:26 INFO stop receive vote response component=consensus
2024/07/11 14:33:26 INFO send vote request to peer component=consensus peer=1
2024/07/11 14:33:26 INFO receive vote request component=consensus peer=0
2024/07/11 14:33:26 INFO receive vote request component=consensus from=127.0.0.1:57328 term=2 "current term"=1
2024/07/11 14:33:26 INFO vote for component=consensus node=1 term=2
2024/07/11 14:33:26 INFO leave leader component=consensus
2024/07/11 14:33:26 INFO become follower component=consensus
2024/07/11 14:33:26 INFO leave leader component=consensus
2024/07/11 14:33:26 INFO get voting component=consensus peer=1
2024/07/11 14:33:26 INFO leave follower state due to heartbeat timeout component=consensus
2024/07/11 14:33:26 INFO leave follower component=consensus
2024/07/11 14:33:26 INFO become candidate component=consensus
2024/07/11 14:33:26 INFO send vote request to peer component=consensus peer=1
2024/07/11 14:33:26 INFO receive vote request component=consensus peer=0
2024/07/11 14:33:26 INFO receive vote request component=consensus from=127.0.0.1:57328 term=3 "current term"=2
2024/07/11 14:33:26 INFO vote for component=consensus node=1 term=3
2024/07/11 14:33:26 INFO get voting component=consensus peer=1
2024/07/11 14:33:26 INFO receive vote component=consensus peer=127.0.0.1:57329
2024/07/11 14:33:26 INFO received more than half of the votes, become leader component=consensus
2024/07/11 14:33:26 INFO leave candidate component=consensus
2024/07/11 14:33:26 INFO become leader component=consensus
panic: send on closed channel

goroutine 26 [running]:
github.com/danl5/goelect/pkg/consensus.(*Consensus).HeartBeat(0x1400040e140, 0x14000122360, 0x14000122378)
        /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.5/pkg/consensus/consensus.go:174 +0x1e8
github.com/danl5/goelect/pkg/consensus.(*Consensus).HandleRequest(0x1400040e140, 0x14000116440, 0x14000124460)
        /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.5/pkg/consensus/consensus.go:117 +0x638
github.com/danl5/goelect/pkg/transport/rpc.(*RPCHandler).Handle(0x1?, 0x1?, 0x0?)
        /Users/dimaxgl/go/pkg/mod/github.com/danl5/goelect@v1.0.5/pkg/transport/rpc/rpc.go:55 +0x2c
reflect.Value.call({0x140001ab440?, 0x140003e80a0?, 0x13?}, {0x104854f84, 0x4}, {0x14000077ef8, 0x3, 0x3?})
        /opt/homebrew/opt/go/libexec/src/reflect/value.go:596 +0x970
reflect.Value.Call({0x140001ab440?, 0x140003e80a0?, 0x140002b9e80?}, {0x140002b9ef8?, 0x14000390630?, 0x1?})
        /opt/homebrew/opt/go/libexec/src/reflect/value.go:380 +0x94
net/rpc.(*service).call(0x140003ec2c0, 0x140003ec280, 0x14000398788, 0x14000398790, 0x140003e0900, 0x140003e68a0, {0x104c0ec00?, 0x14000116440?, 0x140001162c0?}, {0x104c0ec40?, ...}, ...)
        /opt/homebrew/opt/go/libexec/src/net/rpc/server.go:381 +0x204
created by net/rpc.(*Server).ServeCodec in goroutine 77
        /opt/homebrew/opt/go/libexec/src/net/rpc/server.go:478 +0x2c8
exit status 2

```

**Comment by danl5** [comment]
Thank you very much for your information, I will try to reproduce and fix it. :)

**Comment by danl5** [comment]
Hi @dimaxgl, could you help check whether this issue still exists in **v1.0.6**?

Commit: #28

**Comment by dimaxgl** [comment]
@danl5 looks like problem is gone. thx!
